import json
import subprocess

from cofr.synthesis import (
    compute_claim_evidence_counts,
    compute_claim_mentions,
    compute_semantic_staleness,
    generate_current_state,
)
from conftest import run_cofr


def _empty_state():
    return {
        'schema_version': 1,
        'cofr_version': '0.1.0',
        'claims': [],
        'evidence': [],
        'experiments': [],
        'decisions': [],
        'open_questions': [],
        'risks': [],
        'artifacts': [],
    }


def test_compute_claim_evidence_counts():
    evidence = [
        {'id': 'ev_1', 'claim_links': [{'claim_id': 'c_a', 'polarity': 'supports'}]},
        {'id': 'ev_2', 'claim_links': [{'claim_id': 'c_a', 'polarity': 'opposes'}]},
        {'id': 'ev_3', 'claim_links': [{'claim_id': 'c_a', 'polarity': 'supports'}, {'claim_id': 'c_b', 'polarity': 'opposes'}]},
    ]
    counts_a = compute_claim_evidence_counts('c_a', evidence)
    assert counts_a == {'supports': 2, 'opposes': 1}
    counts_b = compute_claim_evidence_counts('c_b', evidence)
    assert counts_b == {'supports': 0, 'opposes': 1}


def test_compute_claim_evidence_counts_excludes_stale_evidence():
    evidence = [
        {'id': 'ev_1', 'claim_links': [{'claim_id': 'c_a', 'polarity': 'supports'}], 'stale': False},
        {'id': 'ev_2', 'claim_links': [{'claim_id': 'c_a', 'polarity': 'supports'}], 'stale': True},
    ]
    counts = compute_claim_evidence_counts('c_a', evidence)
    assert counts == {'supports': 1, 'opposes': 0}


def test_compute_claim_evidence_counts_excludes_deprecated_evidence():
    evidence = [
        {'id': 'ev_1', 'claim_links': [{'claim_id': 'c_a', 'polarity': 'supports'}], 'status': 'active'},
        {'id': 'ev_2', 'claim_links': [{'claim_id': 'c_a', 'polarity': 'supports'}], 'status': 'deprecated'},
    ]
    counts = compute_claim_evidence_counts('c_a', evidence)
    assert counts == {'supports': 1, 'opposes': 0}


def test_compute_claim_mentions_filters_by_id():
    index = {
        'notes/a.md': {'id_mentions': ['c_a', 'c_b']},
        'notes/b.md': {'id_mentions': ['c_b']},
        'notes/c.md': {'id_mentions': []},
    }
    mentions_a = compute_claim_mentions('c_a', index)
    mentions_b = compute_claim_mentions('c_b', index)
    assert mentions_a == ['notes/a.md']
    assert sorted(mentions_b) == ['notes/a.md', 'notes/b.md']


def test_generate_current_state_empty_state_has_placeholder():
    state = _empty_state()
    md = generate_current_state(state, {}, {'project_objective': ''})
    assert 'Generated by cofr' in md
    assert 'project_objective' in md
    assert '0 active claims' in md


def test_generate_current_state_populated_has_correct_stance_line():
    state = _empty_state()
    state['claims'] = [
        {'id': 'c_a', 'status': 'provisionally_supported', 'title': 'A', 'confidence': 'medium'},
        {'id': 'c_b', 'status': 'retired', 'title': 'B', 'confidence': 'low'},
    ]
    state['open_questions'] = [{'id': 'q_a', 'question': 'Q', 'priority': 'high', 'status': 'open'}]
    state['risks'] = [{'id': 'r_a', 'statement': 'R', 'severity': 'medium', 'source': 'authored', 'status': 'open'}]
    md = generate_current_state(state, {}, {'project_objective': 'Find truth'})
    assert '1 active claim' in md
    assert '1 open question' in md
    assert '0 unresolved contradictions' in md
    assert 'r_a' in md
    assert 'Find truth' in md


def test_generate_current_state_stance_counts_contradictions():
    state = _empty_state()
    state['claims'] = [{'id': 'c_a', 'status': 'supported', 'title': 'A', 'confidence': 'medium'}]
    md = generate_current_state(state, {}, {'project_objective': ''})
    assert '1 unresolved contradiction' in md


def test_generate_current_state_section6_renders_computed_contradictions():
    state = _empty_state()
    state['claims'] = [{'id': 'c_a', 'status': 'supported', 'title': 'A', 'confidence': 'medium'}]
    md = generate_current_state(state, {}, {'project_objective': ''})
    section = md.split('## Current contradictions / risks', 1)[1].split('\n## ', 1)[0]
    assert 'Computed contradictions:' in section
    assert 'c_a' in section
    assert 'User-identified risks:' in section


def test_generate_current_state_section6_groups_contradictions_by_rule():
    '''Bug #11: section 6 renders each contradiction rule under its own label,
    matching contradictions.md, instead of one flat bullet list.'''
    state = _empty_state()
    state['claims'] = [
        {'id': 'c_conf', 'status': 'provisionally_supported', 'title': 'Conf', 'confidence': 'medium'},
        {'id': 'c_orphan', 'status': 'supported', 'title': 'Orphan', 'confidence': 'medium'},
    ]
    state['evidence'] = [
        {'id': 'ev_pro', 'status': 'active', 'claim_links': [{'claim_id': 'c_conf', 'polarity': 'supports'}]},
        {'id': 'ev_con', 'status': 'active', 'claim_links': [{'claim_id': 'c_conf', 'polarity': 'opposes'}]},
    ]
    md = generate_current_state(state, {}, {'project_objective': ''})
    section = md.split('## Current contradictions / risks', 1)[1].split('\n## ', 1)[0]
    for label in ('### Evidence conflicts', '### Eroded confidence', '### Orphaned assumptions',
                  '### Decision basis eroded', '### Claims unchanged despite new evidence'):
        assert label in section, f'section 6 missing rule heading {label!r}'


def test_generate_current_state_has_recommended_next_decision_and_actions():
    state = _empty_state()
    state['open_questions'] = [{
        'id': 'q_a', 'question': 'Big question?', 'priority': 'critical',
        'blocking_severity': 'high', 'status': 'open',
        'proposed_resolution': 'Run the discriminating test.',
        'minimum_test': 'One split.',
    }]
    md = generate_current_state(state, {}, {'project_objective': ''})
    assert '## Recommended next decision' in md
    assert 'q_a' in md.split('## Recommended next decision', 1)[1]
    actions = md.split('## Recommended next actions', 1)[1]
    assert 'Run the discriminating test.' in actions
    assert 'minimum test: One split.' in actions


def test_generate_current_state_next_actions_empty_when_no_high_priority():
    state = _empty_state()
    state['open_questions'] = [{'id': 'q_low', 'question': 'Minor?', 'priority': 'low', 'status': 'open'}]
    md = generate_current_state(state, {}, {'project_objective': ''})
    actions = md.split('## Recommended next actions', 1)[1]
    assert 'No high-priority actions.' in actions


def test_generate_current_state_includes_what_would_change_my_mind():
    state = _empty_state()
    state['claims'] = [{
        'id': 'c_a',
        'title': 'A',
        'status': 'provisionally_supported',
        'confidence': 'medium',
        'main_support': 'support text',
        'main_weakness': 'weakness text',
        'what_would_change_my_mind': 'this specific finding',
    }]
    md = generate_current_state(state, {}, {'project_objective': ''})
    assert 'this specific finding' in md
    assert 'support text' in md
    assert 'weakness text' in md


def test_generate_current_state_includes_file_inventory():
    state = _empty_state()
    index = {
        'a.md': {'classification': 'structured', 'id_mentions': []},
        'b.md': {'classification': 'structured', 'id_mentions': []},
        'c.md': {'classification': 'unstructured', 'id_mentions': []},
        'p.pdf': {'classification': 'content_extracted', 'id_mentions': []},
    }
    md = generate_current_state(state, index, {'project_objective': ''})
    assert 'structured: 2' in md
    assert 'unstructured: 1' in md
    assert 'content_extracted: 1' in md


def test_generate_current_state_mentioned_in_lists_paths():
    state = _empty_state()
    state['claims'] = [{
        'id': 'c_a', 'title': 'A', 'status': 'provisionally_supported', 'confidence': 'medium',
        'main_support': '', 'main_weakness': '', 'what_would_change_my_mind': '',
    }]
    index = {
        'notes/scratch.md': {'classification': 'unstructured', 'id_mentions': ['c_a']},
        'papers/x.pdf': {'classification': 'content_extracted', 'id_mentions': ['c_a']},
    }
    md = generate_current_state(state, index, {'project_objective': ''})
    assert 'notes/scratch.md' in md
    assert 'papers/x.pdf' in md


def test_generate_current_state_omits_retired_claims_from_active_section():
    state = _empty_state()
    state['claims'] = [
        {'id': 'c_active', 'title': 'ActiveOne', 'status': 'provisionally_supported', 'confidence': 'medium', 'main_support': '', 'main_weakness': '', 'what_would_change_my_mind': ''},
        {'id': 'c_retired', 'title': 'RetiredOne', 'status': 'retired', 'confidence': 'low', 'main_support': '', 'main_weakness': '', 'what_would_change_my_mind': ''},
    ]
    md = generate_current_state(state, {}, {'project_objective': ''})
    after_active_header = md.split('## Active claims', 1)[1]
    active_section = after_active_header.split('\n## ', 1)[0]
    assert 'ActiveOne' in active_section
    assert 'RetiredOne' not in active_section
    assert '1 active claim' in md


def test_generate_current_state_includes_confidence_trend_and_contradictions():
    state = _empty_state()
    state['claims'] = [{
        'id': 'c_a',
        'title': 'Trend claim',
        'status': 'provisionally_supported',
        'confidence': 'high',
        'last_updated': '2026-01-01T00:00:00Z',
        '_timeline': [
            {'t': '2026-01-01T00:00:00Z', 'c': 'low'},
            {'t': '2026-02-01T00:00:00Z', 'c': 'high'},
        ],
    }]
    state['evidence'] = [{
        'id': 'ev_new',
        'last_updated': '2026-03-01T00:00:00Z',
        'claim_links': [{'claim_id': 'c_a', 'polarity': 'supports'}],
    }]
    md = generate_current_state(state, {}, {'project_objective': ''})
    assert 'confidence trend: low -> high' in md
    assert '## Current contradictions / risks' in md
    assert 'unchanged despite newer linked evidence' in md
    assert '## Semantic staleness' not in md


def test_rebuild_all_timelines_walks_history(tmp_path):
    '''Plan: rebuild walks history snapshots and appends entries.'''
    run_cofr(['init', str(tmp_path)])
    body = '---\ntype: claim\nid: claim_t\nconfidence: low\n---\n\n## Title\n\nT.\n## Statement\n\nS.\n'
    subprocess.run(['cofr', 'add', str(tmp_path)], input=body, capture_output=True, text=True)
    import time
    for conf in ('medium', 'high'):
        pack_path = tmp_path / 'claims.yaml'
        text = pack_path.read_text()
        new_text = text.replace(text[text.index('confidence:'):text.index('\n', text.index('confidence:'))], f'confidence: {conf}')
        pack_path.write_text(new_text)
        time.sleep(1.1)
        subprocess.run(['cofr', 'refresh', str(tmp_path)], capture_output=True, text=True)
    state = json.loads((tmp_path / '.cofr' / 'state.json').read_text())
    claim = [c for c in state['claims'] if c['id'] == 'claim_t'][0]
    pre_rebuild_len = len(claim['_timeline'])
    claim['_timeline'] = []
    claim['_status_timeline'] = []
    (tmp_path / '.cofr' / 'state.json').write_text(json.dumps(state, indent=2, sort_keys=True) + '\n')
    r = run_cofr(['refresh', '--rebuild-timelines', str(tmp_path)])
    assert r.returncode == 0
    state_after = json.loads((tmp_path / '.cofr' / 'state.json').read_text())
    claim_after = [c for c in state_after['claims'] if c['id'] == 'claim_t'][0]
    assert len(claim_after['_timeline']) >= 1


def test_last_diff_reports_pack_record_deletion_as_modified_with_stale_flip(tmp_path):
    '''Plan: source deletion stale-flips the record; surfaces in diff.modified with fields_updated:["stale"], NOT diff.removed (state retains history).'''
    run_cofr(['init', str(tmp_path)])
    (tmp_path / 'evidences').mkdir()
    (tmp_path / 'evidences' / '__misc__.yaml').write_text('- id: ev_a\n  type: evidence\n  summary: E\n')
    subprocess.run(['cofr', 'refresh', str(tmp_path)], capture_output=True, text=True)
    (tmp_path / 'evidences' / '__misc__.yaml').write_text('[]\n')
    r = subprocess.run(['cofr', 'refresh', str(tmp_path)], capture_output=True, text=True)
    assert r.returncode in (0, 1), r.stderr
    diff = json.loads((tmp_path / '.cofr' / 'last_diff.json').read_text())
    modified_entries = [m for m in diff['modified'] if m.get('id') == 'ev_a']
    assert modified_entries
    assert 'stale' in modified_entries[0].get('fields_updated', [])


def test_both_rebuild_flags_run_in_one_invocation(tmp_path):
    '''Plan: --rebuild-renames-log and --rebuild-timelines must both run when passed together.'''
    run_cofr(['init', str(tmp_path)])
    (tmp_path / 'claims.yaml').write_text('- id: claim_a\n  type: claim\n  title: T\n  statement: S\n  confidence: low\n')
    run_cofr(['refresh', str(tmp_path)])
    (tmp_path / 'claims.yaml').write_text('- id: claim_a\n  type: claim\n  title: T\n  statement: S\n  confidence: high\n')
    run_cofr(['refresh', str(tmp_path)])
    r = run_cofr(['refresh', '--rebuild-renames-log', '--rebuild-timelines', str(tmp_path)])
    assert r.returncode in (0, 1), r.stderr
    assert 'rebuild-renames-log' in r.stdout
    assert 'rebuild-timelines' in r.stdout


def test_rebuild_timelines_regenerates_current_state_md(tmp_path):
    '''--rebuild-timelines must regenerate artifacts/current_state.md.'''
    run_cofr(['init', str(tmp_path)])
    (tmp_path / 'claims.yaml').write_text('- id: claim_a\n  type: claim\n  title: TitleA\n  statement: S\n')
    run_cofr(['refresh', str(tmp_path)])
    artifact = tmp_path / 'artifacts' / 'current_state.md'
    artifact.write_text('OLD_PLACEHOLDER\n')
    r = run_cofr(['refresh', '--rebuild-timelines', str(tmp_path)])
    assert r.returncode == 0, r.stderr
    text = artifact.read_text()
    assert 'OLD_PLACEHOLDER' not in text, 'rebuild-timelines must regenerate current_state.md'


def test_rebuild_timelines_regenerates_contradictions_and_next_decision(tmp_path):
    '''Bug #2: --rebuild-timelines must regenerate every state-derived artifact.'''
    run_cofr(['init', str(tmp_path)])
    (tmp_path / 'claims.yaml').write_text('- id: claim_a\n  type: claim\n  title: TitleA\n  statement: S\n')
    run_cofr(['refresh', str(tmp_path)])
    for name in ('contradictions.md', 'next_decision.md'):
        (tmp_path / 'artifacts' / name).write_text('OLD_PLACEHOLDER\n')
    r = run_cofr(['refresh', '--rebuild-timelines', str(tmp_path)])
    assert r.returncode == 0, r.stderr
    for name in ('contradictions.md', 'next_decision.md'):
        assert 'OLD_PLACEHOLDER' not in (tmp_path / 'artifacts' / name).read_text(), name


def test_polarity_changed_includes_evidence_id(tmp_path):
    '''polarity_changed entries must include evidence_id (not just claim_id, old, new).'''
    run_cofr(['init', str(tmp_path)])
    (tmp_path / 'claims.yaml').write_text('- id: claim_a\n  type: claim\n  title: A\n  statement: S\n')
    (tmp_path / 'evidences').mkdir()
    (tmp_path / 'evidences' / 'src.yaml').write_text(
        '- id: ev_a\n  type: evidence\n  evidence_type: paper_note\n  summary: hello\n'
        '  claim_links:\n    - claim_id: claim_a\n      polarity: supports\n'
    )
    run_cofr(['refresh', str(tmp_path)])
    (tmp_path / 'evidences' / 'src.yaml').write_text(
        '- id: ev_a\n  type: evidence\n  evidence_type: paper_note\n  summary: hello\n'
        '  claim_links:\n    - claim_id: claim_a\n      polarity: opposes\n'
    )
    r = run_cofr(['refresh', '--json', str(tmp_path)])
    env = json.loads(r.stdout)
    modified = env['data']['diff']['modified']
    ev_entry = next((m for m in modified if m['id'] == 'ev_a'), None)
    assert ev_entry is not None
    polarity = ev_entry.get('polarity_changed', [])
    assert polarity, 'polarity_changed should be populated'
    assert all('evidence_id' in p for p in polarity), 'each polarity_changed entry must include evidence_id'


def test_rule_a_warns_on_invalid_evidence_timestamp(tmp_path):
    '''Rule A: unparseable evidence last_updated must emit a non-blocking warning.'''
    run_cofr(['init', str(tmp_path)])
    (tmp_path / 'claims.yaml').write_text('- id: claim_a\n  type: claim\n  title: T\n  statement: S\n')
    (tmp_path / 'evidences').mkdir()
    (tmp_path / 'evidences' / 'src.yaml').write_text(
        '- id: ev_a\n  type: evidence\n  evidence_type: paper_note\n  summary: ok\n'
        '  claim_links:\n    - claim_id: claim_a\n      polarity: supports\n'
    )
    run_cofr(['refresh', str(tmp_path)])
    state_path = tmp_path / '.cofr' / 'state.json'
    state = json.loads(state_path.read_text())
    for ev in state['evidence']:
        if ev['id'] == 'ev_a':
            ev['last_updated'] = 'this-is-not-a-timestamp'
    for c in state['claims']:
        if c['id'] == 'claim_a':
            c['last_updated'] = '2026-01-01T00:00:00Z'
    state_path.write_text(json.dumps(state, indent=2, sort_keys=True))
    staleness, warnings = compute_semantic_staleness(state)
    assert any('ev_a' in w or 'this-is-not-a-timestamp' in w for w in warnings), 'rule A should warn on unparseable evidence timestamp'


def test_status_timeline_renders_status_trend_in_current_state(tmp_path):
    run_cofr(['init', str(tmp_path)])
    (tmp_path / 'claims.yaml').write_text('- id: claim_s\n  type: claim\n  title: Status\n  statement: S\n  status: provisionally_supported\n')
    run_cofr(['refresh', str(tmp_path)])
    (tmp_path / 'claims.yaml').write_text('- id: claim_s\n  type: claim\n  title: Status\n  statement: S\n  status: mixed\n')
    run_cofr(['refresh', str(tmp_path)])
    text = (tmp_path / 'artifacts' / 'current_state.md').read_text()
    assert 'status trend: provisionally_supported -> mixed' in text


def test_what_changed_does_not_render_dead_semantic_staleness_section(tmp_path):
    run_cofr(['init', str(tmp_path)])
    (tmp_path / 'claims.yaml').write_text('- id: claim_a\n  type: claim\n  title: T\n  statement: S\n')
    run_cofr(['refresh', str(tmp_path)])
    import time
    time.sleep(1.1)
    (tmp_path / 'evidences').mkdir()
    (tmp_path / 'evidences' / 'src.yaml').write_text(
        '- id: ev_a\n  type: evidence\n  summary: E\n'
        '  claim_links:\n    - claim_id: claim_a\n      polarity: supports\n'
    )
    r = run_cofr(['refresh', '--json', str(tmp_path)])
    env = json.loads(r.stdout)
    assert any('staleness: claim claim_a unchanged' in w for w in env['data']['warnings'])
    artifact = (tmp_path / 'artifacts' / 'what_changed.md').read_text()
    assert '## Semantically stale' not in artifact


def test_diff_tracks_non_status_field_old_new_and_artifact_renders_it(tmp_path):
    run_cofr(['init', str(tmp_path)])
    (tmp_path / 'claims.yaml').write_text('- id: claim_a\n  type: claim\n  title: A\n  statement: S\n  main_support: Old\n')
    run_cofr(['refresh', str(tmp_path)])
    (tmp_path / 'claims.yaml').write_text('- id: claim_a\n  type: claim\n  title: A\n  statement: S\n  main_support: New\n')
    run_cofr(['refresh', str(tmp_path)])
    diff = json.loads((tmp_path / '.cofr' / 'last_diff.json').read_text())
    entry = next(m for m in diff['modified'] if m['id'] == 'claim_a')
    assert entry['field_changes']['main_support'] == {'old': 'Old', 'new': 'New'}
    assert "main_support 'Old' -> 'New'" in (tmp_path / 'artifacts' / 'what_changed.md').read_text()


def test_semantic_staleness_ignores_non_live_evidence():
    state = {
        'claims': [{'id': 'claim_a', 'status': 'provisionally_supported', 'last_updated': '2026-01-01T00:00:00Z'}],
        'evidence': [{'id': 'ev_old', 'status': 'deprecated', 'stale': True, 'last_updated': '2026-02-01T00:00:00Z', 'claim_links': [{'claim_id': 'claim_a'}]}],
        'decisions': [],
    }
    staleness, warnings = compute_semantic_staleness(state)
    assert staleness['claim_unchanged'] == []
    assert warnings == []
