'''Synthesis seam: timestamp helpers, semantic staleness rules, state diff,
timeline rebuild, and rendering of current_state.md and what_changed.md.'''
import json
from datetime import datetime, timezone
from pathlib import Path


HEADER = '<!-- Generated by cofr. Do not edit -- changes will be overwritten on next refresh. -->'
OBJECTIVE_PLACEHOLDER = '(Set `project_objective` in `.cofr/config.yaml` to populate this section.)'

_DIFF_EXCLUDED_FIELDS = {
    'id', 'type', 'parsed_from', 'first_seen', 'last_updated',
    '_timeline', '_status_timeline', '_unknown_fields', '_preserved_user_fields',
}

_QUESTION_PRIORITY_RANK = {'critical': 4, 'high': 3, 'medium': 2, 'low': 1}
_QUESTION_SEVERITY_RANK = {'high': 3, 'medium': 2, 'low': 1}


def parse_timestamp(s):
    '''Parse an ISO-8601 or date string. Returns datetime in UTC or None.'''
    if not s:
        return None
    s = str(s).strip()
    if not s:
        return None
    for fmt in ('%Y-%m-%dT%H:%M:%SZ', '%Y-%m-%dT%H:%M:%S', '%Y-%m-%dT%H:%M:%S%z', '%Y-%m-%d'):
        try:
            dt = datetime.strptime(s, fmt)
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            return dt.astimezone(timezone.utc)
        except ValueError:
            continue
    try:
        dt = datetime.fromisoformat(s.replace('Z', '+00:00'))
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.astimezone(timezone.utc)
    except ValueError:
        return None


def is_timestamp_empty(s):
    return s is None or s == ''


def compute_claim_evidence_counts(claim_id, all_evidence):
    from cofr.domain import is_live
    counts = {'supports': 0, 'opposes': 0}
    for ev in all_evidence:
        if not is_live(ev, type_str='evidence'):
            continue
        for link in ev.get('claim_links', []) or []:
            if link.get('claim_id') == claim_id:
                polarity = link.get('polarity', 'supports')
                if polarity in counts:
                    counts[polarity] += 1
    return counts


def compute_claim_mentions(claim_id, index_dict):
    out = []
    for path in sorted(index_dict):
        entry = index_dict[path]
        if claim_id in (entry.get('id_mentions') or []):
            out.append(path)
    return out


def compute_semantic_staleness(state):
    '''Return (staleness, warnings).

    staleness: {claim_unchanged: [...], decision_basis_eroded: [...]}
    warnings: timestamp-parse failure strings.
    '''
    from cofr.domain import confidence_to_numeric, is_live
    staleness = {'claim_unchanged': [], 'decision_basis_eroded': []}
    warnings = []
    claims = state.get('claims', [])
    evidence = state.get('evidence', [])
    decisions = state.get('decisions', [])

    claims_by_id = {c.get('id'): c for c in claims if c.get('id')}

    for claim in claims:
        if not is_live(claim, type_str='claim'):
            continue
        cid = claim.get('id')
        if not cid:
            continue
        claim_lu_str = claim.get('last_updated', '')
        if is_timestamp_empty(claim_lu_str):
            continue
        claim_lu = parse_timestamp(claim_lu_str)
        if claim_lu is None:
            warnings.append(f"staleness check on {cid}: unparseable timestamp {claim_lu_str!r}; skipping rule")
            continue
        newer_evidence = []
        for ev in evidence:
            if not is_live(ev, type_str='evidence'):
                continue
            if not any((isinstance(link, dict) and link.get('claim_id') == cid) for link in (ev.get('claim_links') or [])):
                continue
            ev_lu = ev.get('last_updated', '')
            if is_timestamp_empty(ev_lu):
                continue
            ev_dt = parse_timestamp(ev_lu)
            if ev_dt is None:
                warnings.append(f"staleness check on {ev.get('id', '?')}: unparseable timestamp {ev_lu!r}; skipping rule")
                continue
            if ev_dt > claim_lu:
                newer_evidence.append(ev.get('id', ''))
        if newer_evidence:
            staleness['claim_unchanged'].append({
                'claim_id': cid,
                'newer_evidence_ids': newer_evidence,
                'newer_count': len(newer_evidence),
                'reason': f'claim last_updated {claim_lu_str} precedes max(linked_evidence.last_updated)',
            })

    for dec in decisions:
        if not is_live(dec, type_str='decision'):
            continue
        dec_id = dec.get('id')
        if not dec_id:
            continue
        ts_str = dec.get('timestamp', '')
        if is_timestamp_empty(ts_str):
            ref_dt_str = dec.get('first_seen', '')
            ref_dt = parse_timestamp(ref_dt_str) if not is_timestamp_empty(ref_dt_str) else None
        else:
            ref_dt = parse_timestamp(ts_str)
            if ref_dt is None:
                warnings.append(f"staleness check on {dec_id}: unparseable timestamp {ts_str!r}; skipping rule")
                continue
        if ref_dt is None:
            continue
        seen_basis_claims = set()
        for cid in (dec.get('depends_on_claim_ids') or []):
            if cid in seen_basis_claims:
                continue
            seen_basis_claims.add(cid)
            claim = claims_by_id.get(cid)
            if not claim:
                continue
            timeline = claim.get('_timeline') or []
            historical_c = None
            for entry in timeline:
                t = parse_timestamp(entry.get('t'))
                if t and t <= ref_dt:
                    historical_c = entry.get('c')
            if historical_c is None and timeline:
                historical_c = timeline[0].get('c')
            current_c = claim.get('confidence')
            hc_num = confidence_to_numeric(historical_c)
            cc_num = confidence_to_numeric(current_c)
            if hc_num is None and historical_c:
                warnings.append(f"staleness check on {dec_id}: non-canonical historical confidence {historical_c!r} for claim {cid}; skipping erosion check")
            if cc_num is None and current_c:
                warnings.append(f"staleness check on {dec_id}: non-canonical current confidence {current_c!r} for claim {cid}; skipping erosion check")
            if hc_num is not None and cc_num is not None and (cc_num - hc_num) < -0.2:
                staleness['decision_basis_eroded'].append({
                    'decision_id': dec_id,
                    'depended_on_claim_id': cid,
                    'mode': 'confidence_drop',
                    'historical_value': historical_c,
                    'current_value': current_c,
                    'reference_time': ts_str or dec.get('first_seen', ''),
                    'reason': f'confidence dropped {historical_c} -> {current_c}',
                })
            status_timeline = claim.get('_status_timeline') or []
            historical_status = None
            for entry in status_timeline:
                t = parse_timestamp(entry.get('t'))
                if t and t <= ref_dt:
                    historical_status = entry.get('s')
            if historical_status is None and status_timeline:
                historical_status = status_timeline[0].get('s')
            current_status = claim.get('status')
            if historical_status is not None and current_status is not None and historical_status != current_status:
                staleness['decision_basis_eroded'].append({
                    'decision_id': dec_id,
                    'depended_on_claim_id': cid,
                    'mode': 'status_change',
                    'historical_value': historical_status,
                    'current_value': current_status,
                    'reference_time': ts_str or dec.get('first_seen', ''),
                    'reason': f'basis claim status changed {historical_status} -> {current_status} after decision time',
                })
    return staleness, warnings


_CONTRADICTION_SECTIONS = [
    ('evidence_conflict', 'Evidence conflicts'),
    ('eroded_confidence', 'Eroded confidence'),
    ('orphaned_assumption', 'Orphaned assumptions'),
    ('decision_basis_eroded', 'Decision basis eroded'),
    ('claim_unchanged', 'Claims unchanged despite new evidence'),
]
_CONTRADICTION_RULES = tuple(key for key, _ in _CONTRADICTION_SECTIONS)


def _links_with_polarity(evidence_rec, claim_id, polarity):
    for link in evidence_rec.get('claim_links') or []:
        if isinstance(link, dict) and link.get('claim_id') == claim_id and link.get('polarity', 'supports') == polarity:
            return True
    return False


def _evidence_link_polarity(evidence_rec, claim_id):
    '''Return the polarity an evidence record links to claim_id with, or None if unlinked.'''
    for link in evidence_rec.get('claim_links') or []:
        if isinstance(link, dict) and link.get('claim_id') == claim_id:
            return link.get('polarity', 'supports')
    return None


def compute_falsification_review(state):
    '''Return falsification-review records -- the agent-judged rule-6 surface.

    For each live claim with a non-empty what_would_change_my_mind and one or
    more linked live evidence records, pair the falsification condition with
    that evidence. cofr issues no verdict; the consuming agent judges whether
    the evidence meets the condition. Pure function of state.
    '''
    from cofr.domain import is_live

    live_evidence = [e for e in state.get('evidence', []) if e.get('id') and is_live(e, type_str='evidence')]
    review = []
    for claim in state.get('claims', []):
        if not claim.get('id') or not is_live(claim, type_str='claim'):
            continue
        wwcmm = claim.get('what_would_change_my_mind', '') or ''
        if not wwcmm.strip():
            continue
        cid = claim['id']
        linked = []
        for e in live_evidence:
            polarity = _evidence_link_polarity(e, cid)
            if polarity is None:
                continue
            linked.append({
                'id': e['id'],
                'polarity': polarity,
                'strength': e.get('strength', ''),
                'summary': e.get('summary', ''),
            })
        if not linked:
            continue
        linked.sort(key=lambda x: x['id'])
        review.append({
            'claim_id': cid,
            'claim_title': claim.get('title', ''),
            'statement': claim.get('statement', ''),
            'what_would_change_my_mind': wwcmm,
            'evidence': linked,
        })
    review.sort(key=lambda r: r['claim_id'])
    return review


def compute_contradictions(state):
    '''Return (contradictions, warnings) -- the five mechanical contradiction rules.

    Rules 1-2 (claim_unchanged, decision_basis_eroded) come from
    compute_semantic_staleness; rules 3-5 (evidence_conflict, eroded_confidence,
    orphaned_assumption) are computed here. Pure function of state -- no diff,
    no LLM, no filesystem. Every record carries a uniform shape: rule, cited_ids,
    reason, plus rule-specific fields.
    '''
    from cofr.domain import is_live

    contradictions = {rule: [] for rule in _CONTRADICTION_RULES}
    staleness, warnings = compute_semantic_staleness(state)
    warnings = list(warnings)

    for entry in staleness.get('claim_unchanged', []):
        rec = dict(entry)
        rec['rule'] = 'claim_unchanged'
        rec['cited_ids'] = sorted({rec.get('claim_id')} - {None} | set(rec.get('newer_evidence_ids') or []))
        contradictions['claim_unchanged'].append(rec)
    for entry in staleness.get('decision_basis_eroded', []):
        rec = dict(entry)
        rec['rule'] = 'decision_basis_eroded'
        rec['cited_ids'] = sorted({rec.get('decision_id'), rec.get('depended_on_claim_id')} - {None})
        contradictions['decision_basis_eroded'].append(rec)

    evidence = state.get('evidence', [])
    live_claims = [c for c in state.get('claims', []) if c.get('id') and is_live(c, type_str='claim')]
    live_evidence = [e for e in evidence if e.get('id') and is_live(e, type_str='evidence')]

    for claim in live_claims:
        cid = claim['id']
        supports = {e['id'] for e in live_evidence if _links_with_polarity(e, cid, 'supports')}
        opposes = {e['id'] for e in live_evidence if _links_with_polarity(e, cid, 'opposes')}
        if supports and opposes and len(supports | opposes) >= 2:
            evidence_ids = sorted(supports | opposes)
            contradictions['evidence_conflict'].append({
                'rule': 'evidence_conflict',
                'claim_id': cid,
                'evidence_ids': evidence_ids,
                'cited_ids': sorted({cid} | supports | opposes),
                'reason': f'claim {cid} has {len(supports)} supporting and {len(opposes)} opposing live evidence record(s)',
            })

    for claim in live_claims:
        if claim.get('confidence') != 'high':
            continue
        cid = claim['id']
        claim_lu_str = claim.get('last_updated', '')
        if is_timestamp_empty(claim_lu_str):
            continue
        claim_lu = parse_timestamp(claim_lu_str)
        if claim_lu is None:
            warnings.append(f'contradiction check on {cid}: unparseable timestamp {claim_lu_str!r}; skipping eroded-confidence rule')
            continue
        newer_opposing = []
        for e in live_evidence:
            if not _links_with_polarity(e, cid, 'opposes'):
                continue
            ev_lu_str = e.get('last_updated', '')
            if is_timestamp_empty(ev_lu_str):
                continue
            ev_lu = parse_timestamp(ev_lu_str)
            if ev_lu is None:
                warnings.append(f"contradiction check on {e['id']}: unparseable timestamp {ev_lu_str!r}; skipping eroded-confidence rule")
                continue
            if ev_lu > claim_lu:
                newer_opposing.append(e['id'])
        if newer_opposing:
            newer_opposing = sorted(newer_opposing)
            contradictions['eroded_confidence'].append({
                'rule': 'eroded_confidence',
                'claim_id': cid,
                'evidence_ids': newer_opposing,
                'cited_ids': sorted({cid} | set(newer_opposing)),
                'reason': f'high-confidence claim {cid} has opposing evidence updated after the claim was last re-evaluated',
            })

    for claim in live_claims:
        if claim.get('status') != 'supported':
            continue
        cid = claim['id']
        counts = compute_claim_evidence_counts(cid, evidence)
        if counts['supports'] == 0 and counts['opposes'] == 0:
            contradictions['orphaned_assumption'].append({
                'rule': 'orphaned_assumption',
                'claim_id': cid,
                'cited_ids': [cid],
                'reason': f'claim {cid} has status supported but zero live evidence linking to it',
            })

    contradictions['claim_unchanged'].sort(key=lambda r: r.get('claim_id') or '')
    contradictions['decision_basis_eroded'].sort(key=lambda r: (r.get('decision_id') or '', r.get('depended_on_claim_id') or '', r.get('mode') or ''))
    contradictions['evidence_conflict'].sort(key=lambda r: r['claim_id'])
    contradictions['eroded_confidence'].sort(key=lambda r: r['claim_id'])
    contradictions['orphaned_assumption'].sort(key=lambda r: r['claim_id'])
    return contradictions, warnings


def _blank_computed_risk(**kw):
    risk = {
        'id': '', 'statement': '', 'severity': 'medium',
        'related_claim_ids': [], 'related_decision_ids': [],
        'recommended_resolution': '', 'status': 'open', 'source': 'computed',
        'parsed_from': '', 'first_seen': '', 'last_updated': '',
        'stale': False, 'extra_sections': {},
    }
    risk.update(kw)
    return risk


def compute_computed_risks(state, contradictions=None):
    '''Return (computed_risk_dicts, warnings).

    Projects each rule-1-5 contradiction record into a transient Risk record
    (source=computed). Never persisted to state.json, never in history or diffs.
    Ids are deterministic so repeated calls are byte-stable.

    When `contradictions` is supplied (already computed for this state) it is
    reused instead of recomputed; the caller then owns the contradiction-detection
    warnings, and the returned warnings carry only computed-risk id collisions.
    '''
    if contradictions is None:
        contradictions, warnings = compute_contradictions(state)
    else:
        warnings = []
    warnings = list(warnings)
    risks = []
    for entry in contradictions['claim_unchanged']:
        cid = entry['claim_id']
        risks.append(_blank_computed_risk(
            id=f'risk_computed_claim_unchanged_{cid}',
            statement=entry['reason'], severity='medium', related_claim_ids=[cid],
        ))
    for entry in contradictions['decision_basis_eroded']:
        did = entry['decision_id']
        clid = entry.get('depended_on_claim_id', '') or ''
        mode = entry.get('mode', '') or ''
        risks.append(_blank_computed_risk(
            id=f'risk_computed_decision_basis_eroded_{did}_{clid}_{mode}',
            statement=entry['reason'], severity='high',
            related_claim_ids=[clid] if clid else [], related_decision_ids=[did],
        ))
    for entry in contradictions['evidence_conflict']:
        cid = entry['claim_id']
        risks.append(_blank_computed_risk(
            id=f'risk_computed_evidence_conflict_{cid}',
            statement=entry['reason'], severity='high', related_claim_ids=[cid],
        ))
    for entry in contradictions['eroded_confidence']:
        cid = entry['claim_id']
        risks.append(_blank_computed_risk(
            id=f'risk_computed_eroded_confidence_{cid}',
            statement=entry['reason'], severity='medium', related_claim_ids=[cid],
        ))
    for entry in contradictions['orphaned_assumption']:
        cid = entry['claim_id']
        risks.append(_blank_computed_risk(
            id=f'risk_computed_orphaned_assumption_{cid}',
            statement=entry['reason'], severity='low', related_claim_ids=[cid],
        ))
    authored_ids = {
        item.get('id')
        for collection_key in ('claims', 'evidence', 'experiments', 'decisions', 'open_questions', 'risks')
        for item in state.get(collection_key, [])
        if item.get('id')
    }
    seen = set()
    deduped = []
    for r in risks:
        if r['id'] in authored_ids:
            warnings.append(f"computed-risk id collision with authored state: {r['id']!r}; dropping computed risk")
            continue
        if r['id'] in seen:
            warnings.append(f"computed-risk id collision: {r['id']!r} generated more than once; dropping duplicate")
            continue
        seen.add(r['id'])
        deduped.append(r)
    deduped.sort(key=lambda r: r['id'])
    return deduped, warnings


def rank_next_decisions(state, contradictions=None):
    '''Return (ranked, rationale_lines, warnings).

    Ranks open questions and decisions with eroded basis by the documented
    scoring formula. The ranking is a deterministic scaffold -- the consuming
    agent makes the final recommendation. Pure function of state.

    When `contradictions` is supplied it is reused instead of recomputed; the
    caller then owns the contradiction-detection warnings.
    '''
    from cofr.domain import is_live

    if contradictions is None:
        contradictions, warnings = compute_contradictions(state)
    else:
        warnings = []
    warnings = list(warnings)
    claims_by_id = {c.get('id'): c for c in state.get('claims', []) if c.get('id')}

    def _related(ids, live_only=False):
        out = []
        for cid in ids or []:
            c = claims_by_id.get(cid)
            if not c:
                continue
            if live_only and not is_live(c, type_str='claim'):
                continue
            out.append({'id': cid, 'status': c.get('status', ''), 'confidence': c.get('confidence', '')})
        return out

    ranked = []
    for q in state.get('open_questions', []):
        if not q.get('id') or q.get('status') != 'open' or not is_live(q, type_str='question'):
            continue
        priority_score = _QUESTION_PRIORITY_RANK.get(q.get('priority', ''), 0)
        severity_score = _QUESTION_SEVERITY_RANK.get(q.get('blocking_severity', ''), 0)
        related = _related(q.get('related_claim_ids'), live_only=True)
        weak = sum(1 for r in related if r['status'] in ('mixed', 'unsupported'))
        ranked.append({
            'kind': 'question', 'id': q['id'],
            'score': priority_score + severity_score + weak,
            'score_breakdown': {'priority': priority_score, 'blocking_severity': severity_score,
                                'mixed_unsupported_claims': weak, 'stale_decision_bonus': 0},
            'record': q, 'related_claims': related, 'eroded_basis': [],
        })

    decisions_by_id = {d.get('id'): d for d in state.get('decisions', []) if d.get('id')}
    eroded_by_decision = {}
    for e in contradictions['decision_basis_eroded']:
        if e.get('decision_id'):
            eroded_by_decision.setdefault(e['decision_id'], []).append(e)
    for did in sorted(eroded_by_decision):
        dec = decisions_by_id.get(did)
        if dec is None or not is_live(dec, type_str='decision'):
            continue
        ranked.append({
            'kind': 'decision', 'id': did, 'score': 2,
            'score_breakdown': {'priority': 0, 'blocking_severity': 0,
                                'mixed_unsupported_claims': 0, 'stale_decision_bonus': 2},
            'record': dec, 'related_claims': _related(dec.get('depends_on_claim_ids'), live_only=True),
            'eroded_basis': eroded_by_decision[did],
        })

    ranked.sort(key=lambda x: (-x['score'], x['id']))

    rationale_lines = [
        'Open questions scored by priority (critical=4, high=3, medium=2, low=1)',
        '  + blocking_severity (high=3, medium=2, low=1)',
        '  + count of related claims with status mixed or unsupported.',
        'Decisions with eroded basis get a base score bonus of +2.',
        'Ties broken by ascending id.',
    ]
    for entry in ranked:
        b = entry['score_breakdown']
        if entry['kind'] == 'question':
            rationale_lines.append(
                f"{entry['id']}: score {entry['score']} "
                f"(priority {b['priority']} + severity {b['blocking_severity']} + {b['mixed_unsupported_claims']} weak claim(s))"
            )
        else:
            rationale_lines.append(f"{entry['id']}: score {entry['score']} (eroded-basis decision, +2 bonus)")
    return ranked, rationale_lines, warnings


def _index_by_id(items):
    return {item.get('id'): item for item in items if item.get('id')}


def compute_diff(prior_state, current_state, explicit_renames=None):
    '''Compute state diff: {added, removed, modified, renamed}.

    Same-id relocations classify as modified with fields_updated:['parsed_from'].
    Transitions from live to non-live classify as removed; cofr keeps the record
    in state for history, but the diff category is the user-facing removal event.
    Renames consume from explicit_renames (at most one).
    diff.removed = records ABSENT from current state (distinct from
    changes.removed which is stale-marked-this-refresh).
    The caller merges broken_references, refresh_summary, and generated_at into
    the sidecar (.cofr/last_diff.json) -- those are NOT returned by compute_diff.
    '''
    explicit_renames = explicit_renames or []
    renamed_ids = {(r['type'], r['new_id']) for r in explicit_renames}
    renamed_old_ids = {(r['type'], r['old_id']) for r in explicit_renames}
    rename_pairs = [{'type': r['type'], 'old_id': r['old_id'], 'new_id': r['new_id']} for r in explicit_renames]

    diff = {
        'added': [], 'removed': [], 'modified': [], 'renamed': rename_pairs,
    }

    type_to_collection = {
        'claim': 'claims', 'evidence': 'evidence', 'experiment': 'experiments',
        'decision': 'decisions', 'question': 'open_questions', 'risk': 'risks',
    }

    for type_str, ck in type_to_collection.items():
        prior_by_id = _index_by_id(prior_state.get(ck, []))
        curr_by_id = _index_by_id(current_state.get(ck, []))
        for rid in curr_by_id:
            if rid in prior_by_id:
                continue
            if (type_str, rid) in renamed_ids:
                continue
            diff['added'].append({'type': type_str, 'id': rid})
        for rid in prior_by_id:
            if rid in curr_by_id:
                continue
            if (type_str, rid) in renamed_old_ids:
                continue
            diff['removed'].append({'type': type_str, 'id': rid})
        for rid in curr_by_id:
            if rid not in prior_by_id:
                continue
            prior_rec = prior_by_id[rid]
            curr_rec = curr_by_id[rid]
            fields_changed = []
            field_changes = {}
            entry = {'type': type_str, 'id': rid}
            diffable_fields = (set(prior_rec) | set(curr_rec)) - _DIFF_EXCLUDED_FIELDS
            for f in sorted(diffable_fields):
                if prior_rec.get(f) != curr_rec.get(f):
                    fields_changed.append(f)
                    field_changes[f] = {'old': prior_rec.get(f), 'new': curr_rec.get(f)}
                    if f == 'status':
                        entry['status_changed'] = field_changes[f]
                    elif f == 'confidence':
                        entry['confidence_changed'] = field_changes[f]
            if bool(prior_rec.get('stale')) != bool(curr_rec.get('stale')):
                fields_changed.append('stale')
                field_changes['stale'] = {'old': bool(prior_rec.get('stale')), 'new': bool(curr_rec.get('stale'))}
            if prior_rec.get('parsed_from') != curr_rec.get('parsed_from'):
                fields_changed.append('parsed_from')
                field_changes['parsed_from'] = {'old': prior_rec.get('parsed_from'), 'new': curr_rec.get('parsed_from')}
            evidence_subfields_changed = False
            if type_str == 'evidence':
                prior_links = {l.get('claim_id'): l.get('polarity', 'supports') for l in (prior_rec.get('claim_links') or []) if isinstance(l, dict)}
                curr_links = {l.get('claim_id'): l.get('polarity', 'supports') for l in (curr_rec.get('claim_links') or []) if isinstance(l, dict)}
                added_ev = sorted(set(curr_links) - set(prior_links))
                removed_ev = sorted(set(prior_links) - set(curr_links))
                polarity_changes = [
                    {'evidence_id': rid, 'claim_id': k, 'old': prior_links[k], 'new': curr_links[k]}
                    for k in sorted(set(prior_links) & set(curr_links))
                    if prior_links[k] != curr_links[k]
                ]
                if added_ev:
                    entry['evidence_added'] = added_ev
                    entry['evidence_link_added'] = added_ev
                    evidence_subfields_changed = True
                if removed_ev:
                    entry['evidence_removed'] = removed_ev
                    entry['evidence_link_removed'] = removed_ev
                    evidence_subfields_changed = True
                if polarity_changes:
                    entry['polarity_changed'] = polarity_changes
                    entry['evidence_polarity_changed'] = polarity_changes
                    evidence_subfields_changed = True
            if fields_changed or evidence_subfields_changed:
                if fields_changed:
                    entry['fields_updated'] = fields_changed
                    entry['field_changes'] = field_changes
                diff['modified'].append(entry)
    return diff


def _composed_rename_map(project_path):
    '''Build the composed rename map from .cofr/renames.json.

    Walks entries in detected_at order; transitively composes A->B then B->C
    into composed[A]=C and composed[B]=C.
    '''
    composed = {}
    log_path = Path(project_path) / '.cofr' / 'renames.json'
    if not log_path.is_file():
        return composed
    try:
        data = json.loads(log_path.read_text(encoding='utf-8'))
    except (json.JSONDecodeError, OSError):
        return composed
    entries = sorted(data.get('renames', []), key=lambda e: e.get('detected_at', ''))
    for entry in entries:
        if entry.get('type') != 'claim':
            continue
        old_id = entry.get('old_id')
        new_id = entry.get('new_id')
        if not old_id or not new_id:
            continue
        for k, v in list(composed.items()):
            if v == old_id:
                composed[k] = new_id
        composed[old_id] = new_id
    return composed


def rebuild_all_timelines(state, project_path):
    '''Rebuild _timeline and _status_timeline for every claim by walking history snapshots.

    Returns (state, config_warnings) so callers can surface malformed config.yaml warnings.
    '''
    from cofr.state import _retain_timeline_entries, load_config

    project_path = Path(project_path)
    composed = _composed_rename_map(project_path)
    config, config_warnings = load_config(project_path)

    for c in state.get('claims', []):
        c['_timeline'] = []
        c['_status_timeline'] = []

    history_dir = project_path / '.cofr' / 'history'
    snapshots = sorted(history_dir.glob('*.json')) if history_dir.is_dir() else []

    def _resolved(rid):
        return composed.get(rid, rid)

    state_claims_by_id = {c.get('id'): c for c in state.get('claims', []) if c.get('id')}

    def _append_entry(target_claim, t_value, c_value, s_value):
        if c_value:
            tl = target_claim['_timeline']
            if not tl or tl[-1].get('c') != c_value:
                tl.append({'t': t_value, 'c': c_value})
        if s_value:
            stl = target_claim['_status_timeline']
            if not stl or stl[-1].get('s') != s_value:
                stl.append({'t': t_value, 's': s_value})

    for snap_path in snapshots:
        try:
            snap = json.loads(snap_path.read_text(encoding='utf-8'))
        except (json.JSONDecodeError, OSError):
            continue
        for snap_claim in snap.get('claims', []):
            historical_id = snap_claim.get('id')
            if not historical_id:
                continue
            resolved = _resolved(historical_id)
            target = state_claims_by_id.get(resolved)
            if target is None:
                continue
            t = snap_claim.get('last_updated') or snap_claim.get('first_seen') or ''
            _append_entry(target, t, snap_claim.get('confidence'), snap_claim.get('status'))

    for c in state.get('claims', []):
        t = c.get('last_updated') or c.get('first_seen') or ''
        _append_entry(c, t, c.get('confidence'), c.get('status'))
        c['_timeline'] = _retain_timeline_entries(c['_timeline'], config)
        c['_status_timeline'] = _retain_timeline_entries(c['_status_timeline'], config)

    return state, config_warnings


def _plural(n, singular, plural=None):
    plural = plural or (singular + 's')
    return f'{n} {singular if n == 1 else plural}'


def _trend_line(timeline, value_key):
    if len(timeline) < 2:
        return ''
    values = [entry.get(value_key) for entry in timeline if entry.get(value_key)]
    if len(values) < 2:
        return ''
    parts = [' -> '.join(values)]
    first = parse_timestamp(timeline[0].get('t'))
    last = parse_timestamp(timeline[-1].get('t'))
    if first and last:
        days = max((last - first).days, 0)
        parts.append(f'({len(values)} steps over {days}d)')
    else:
        parts.append(f'({len(values)} steps)')
    return ' '.join(parts)


def _confidence_trend_line(timeline):
    return _trend_line(timeline, 'c')


def _status_trend_line(timeline):
    return _trend_line(timeline, 's')


def _render_claim_block(claim, support_count, oppose_count, mentions):
    lines = []
    title = claim.get('title') or claim.get('id')
    lines.append(f'### {title}')
    lines.append('')
    lines.append(f'- id: {claim.get('id', '')}')
    lines.append(f'- status: {claim.get('status', '')}')
    lines.append(f'- confidence: {claim.get('confidence', '')}')
    trend = _confidence_trend_line(claim.get('_timeline') or [])
    if trend:
        lines.append(f'- confidence trend: {trend}')
    status_trend = _status_trend_line(claim.get('_status_timeline') or [])
    if status_trend:
        lines.append(f'- status trend: {status_trend}')
    lines.append(f'- supporting evidence: {support_count}')
    lines.append(f'- counter evidence: {oppose_count}')
    statement = claim.get('statement', '')
    if statement:
        lines.append('')
        lines.append('Statement:')
        lines.append('')
        lines.append(statement)
    main_support = claim.get('main_support', '')
    if main_support:
        lines.append('')
        lines.append('Main support:')
        lines.append('')
        lines.append(main_support)
    main_weakness = claim.get('main_weakness', '')
    if main_weakness:
        lines.append('')
        lines.append('Main weakness:')
        lines.append('')
        lines.append(main_weakness)
    wwcmm = claim.get('what_would_change_my_mind', '')
    if wwcmm:
        lines.append('')
        lines.append('What would change my mind:')
        lines.append('')
        lines.append(wwcmm)
    if mentions:
        lines.append('')
        lines.append('Also mentioned in:')
        for m in mentions:
            lines.append(f'- {m}')
    return '\n'.join(lines)


def _render_question_block(q):
    lines = [f'### {q.get('id', 'question')}']
    lines.append('')
    lines.append(f'- priority: {q.get('priority', '')}')
    lines.append(f'- blocking_severity: {q.get('blocking_severity', '')}')
    lines.append(f'- status: {q.get('status', '')}')
    question_text = q.get('question', '')
    if question_text:
        lines.append('')
        lines.append('Question:')
        lines.append('')
        lines.append(question_text)
    if q.get('blocking_impact'):
        lines.append('')
        lines.append('Blocking impact:')
        lines.append('')
        lines.append(q['blocking_impact'])
    if q.get('related_claim_ids'):
        lines.append('')
        lines.append('Related claims:')
        for c in q['related_claim_ids']:
            lines.append(f'- {c}')
    if q.get('minimum_test'):
        lines.append('')
        lines.append('Minimum test:')
        lines.append('')
        lines.append(q['minimum_test'])
    return '\n'.join(lines)


def _rank_questions(questions):
    '''Rank by (priority desc, blocking_severity desc, id asc) per plan §Synthesis §5.'''
    return sorted(
        questions,
        key=lambda q: (
            -_QUESTION_PRIORITY_RANK.get(q.get('priority', ''), 0),
            -_QUESTION_SEVERITY_RANK.get(q.get('blocking_severity', ''), 0),
            q.get('id', ''),
        ),
    )


def _render_risk_block(r):
    lines = [f'### {r.get('id', '')}']
    lines.append('')
    lines.append(f'- severity: {r.get('severity', '')}')
    lines.append(f'- status: {r.get('status', '')}')
    if r.get('statement'):
        lines.append('')
        lines.append(r['statement'])
    if r.get('related_claim_ids'):
        lines.append('')
        lines.append('Related claims: ' + ', '.join(r['related_claim_ids']))
    if r.get('related_decision_ids'):
        lines.append('Related decisions: ' + ', '.join(r['related_decision_ids']))
    if r.get('recommended_resolution'):
        lines.append('')
        lines.append('Recommended resolution:')
        lines.append('')
        lines.append(r['recommended_resolution'])
    return '\n'.join(lines)


def generate_current_state(state, index, config, broken_references=None, last_diff=None):
    from cofr.domain import is_live
    objective = config.get('project_objective') or OBJECTIVE_PLACEHOLDER
    claims = state.get('claims', [])
    evidence = state.get('evidence', [])
    questions = [q for q in state.get('open_questions', []) if is_live(q, type_str='question')]
    risks = [r for r in state.get('risks', []) if r.get('source', 'authored') == 'authored' and is_live(r, type_str='risk')]
    active_claims = [c for c in claims if is_live(c, type_str='claim')]
    contradictions, contradiction_warnings = compute_contradictions(state)
    contradiction_count = sum(len(v) for v in contradictions.values())

    parts = []
    parts.append(HEADER)
    parts.append('')
    parts.append('# Current state')
    parts.append('')
    parts.append('## Core objective')
    parts.append('')
    parts.append(objective)
    parts.append('')
    parts.append('## Current project stance')
    parts.append('')
    parts.append(
        f'{_plural(len(active_claims), 'active claim')}, '
        f'{_plural(len(questions), 'open question')}, '
        f'{_plural(contradiction_count, 'unresolved contradiction')}.'
    )
    parts.append('')

    parts.append('## Active claims')
    parts.append('')
    if not active_claims:
        parts.append('No active claims tracked yet.')
    else:
        for claim in active_claims:
            counts = compute_claim_evidence_counts(claim['id'], evidence)
            mentions = compute_claim_mentions(claim['id'], index)
            parts.append(_render_claim_block(claim, counts['supports'], counts['opposes'], mentions))
            parts.append('')
    parts.append('')

    parts.append('## What changed recently')
    parts.append('')
    if not last_diff:
        parts.append('No diff sidecar found; run `cofr refresh` to populate.')
    else:
        added = last_diff.get('added') or []
        removed = last_diff.get('removed') or []
        modified = last_diff.get('modified') or []
        renamed = last_diff.get('renamed') or []
        if not (added or removed or modified or renamed):
            parts.append('No changes since last refresh.')
        else:
            for it in added[:10]:
                parts.append(f"- added {it.get('type', '')} {it.get('id', '')}")
            for it in removed[:10]:
                parts.append(f"- removed {it.get('type', '')} {it.get('id', '')}")
            for it in modified[:10]:
                fields = it.get('fields_updated') or []
                tag = ', '.join(fields[:4]) if fields else 'changed'
                parts.append(f"- modified {it.get('type', '')} {it.get('id', '')} ({tag})")
            for it in renamed[:10]:
                parts.append(f"- renamed {it.get('type', '')} {it.get('old_id', '')} -> {it.get('new_id', '')}")
            total = len(added) + len(removed) + len(modified) + len(renamed)
            shown = min(len(added), 10) + min(len(removed), 10) + min(len(modified), 10) + min(len(renamed), 10)
            if total > shown:
                parts.append(f'- (+{total - shown} more — see artifacts/what_changed.md)')
    parts.append('')

    parts.append('## Top unresolved questions')
    parts.append('')
    if not questions:
        parts.append('No open questions.')
    else:
        for q in _rank_questions(questions):
            parts.append(_render_question_block(q))
            parts.append('')
    parts.append('')

    parts.append('## Current contradictions / risks')
    parts.append('')
    parts.append('Computed contradictions:')
    parts.append('')
    parts.extend(_render_computed_contradiction_body(contradictions))
    if contradiction_warnings:
        parts.append('Detection warnings:')
        parts.append('')
        for w in contradiction_warnings:
            parts.append(f'- {w}')
        parts.append('')
    parts.append('User-identified risks:')
    parts.append('')
    if not risks:
        parts.append('No user-authored risks.')
    else:
        for r in risks:
            parts.append(_render_risk_block(r))
            parts.append('')
    parts.append('')

    parts.append('## Broken references')
    parts.append('')
    if not broken_references:
        parts.append('None.')
    else:
        for ref in broken_references:
            parts.append(f'- {ref}')
    parts.append('')

    parts.append('## File inventory')
    parts.append('')
    inv = {}
    for entry in index.values():
        cls = entry.get('classification', 'unknown')
        inv[cls] = inv.get(cls, 0) + 1
    if inv:
        for cls in sorted(inv):
            parts.append(f'- {cls}: {inv[cls]}')
    else:
        parts.append('No files indexed.')
    parts.append('')

    parts.append('## Recommended next decision')
    parts.append('')
    ranked, _rationale, _w = rank_next_decisions(state, contradictions=contradictions)
    if not ranked:
        parts.append('No recommended decision.')
    else:
        top = ranked[0]
        parts.append(f"- {top['kind']} {top['id']} (score {top['score']})")
    parts.append('')

    parts.append('## Recommended next actions')
    parts.append('')
    action_questions = _rank_questions([
        q for q in questions
        if q.get('status') == 'open' and q.get('priority') in ('high', 'critical')
    ])
    if not action_questions:
        parts.append('No high-priority actions.')
    else:
        for q in action_questions:
            resolution = q.get('proposed_resolution') or ''
            if resolution:
                parts.append(f'- {resolution}')
            else:
                parts.append(f"- Resolve: {q.get('question', '')}")
            if q.get('minimum_test'):
                parts.append(f"  - minimum test: {q['minimum_test']}")
    parts.append('')

    return '\n'.join(parts) + '\n'


def generate_what_changed(last_diff_dict, project_path):
    '''Render artifacts/what_changed.md from the sidecar dict.'''
    parts = []
    parts.append(HEADER)
    parts.append('')
    parts.append('# What changed')
    parts.append('')
    parts.append(f"Generated at: {last_diff_dict.get('generated_at', '')}")
    parts.append('')
    summary = last_diff_dict.get('refresh_summary') or {}
    parts.append('## Refresh summary')
    parts.append('')
    for k in sorted(summary):
        parts.append(f'- {k}: {summary[k]}')
    parts.append('')
    sections = [
        ('Added', last_diff_dict.get('added') or []),
        ('Removed', last_diff_dict.get('removed') or []),
        ('Modified', last_diff_dict.get('modified') or []),
        ('Renamed', last_diff_dict.get('renamed') or []),
    ]
    for label, items in sections:
        parts.append(f'## {label}')
        parts.append('')
        if not items:
            parts.append('None.')
        else:
            for it in items:
                if 'old_id' in it:
                    parts.append(f"- {it['type']}: {it['old_id']} -> {it['new_id']}")
                elif 'claim_id' in it or 'decision_id' in it:
                    if 'claim_id' in it:
                        parts.append(f"- claim: {it.get('claim_id', '')} ({it.get('reason', '')})")
                    else:
                        parts.append(f"- decision: {it.get('decision_id', '')} ({it.get('reason', '')})")
                else:
                    line = f"- {it['type']}: {it['id']}"
                    extras = []
                    if it.get('reason'):
                        extras.append(str(it['reason']))
                    if it.get('status_changed'):
                        sc = it['status_changed']
                        extras.append(f"status {sc['old']} -> {sc['new']}")
                    if it.get('confidence_changed'):
                        cc = it['confidence_changed']
                        extras.append(f"confidence {cc['old']} -> {cc['new']}")
                    for field_name, change in sorted((it.get('field_changes') or {}).items()):
                        if field_name in ('status', 'confidence'):
                            continue
                        extras.append(f"{field_name} {change.get('old')!r} -> {change.get('new')!r}")
                    if it.get('evidence_link_added'):
                        extras.append(f"evidence links added {it['evidence_link_added']}")
                    if it.get('evidence_link_removed'):
                        extras.append(f"evidence links removed {it['evidence_link_removed']}")
                    if it.get('evidence_polarity_changed'):
                        changes = [
                            f"{c['claim_id']} {c['old']} -> {c['new']}"
                            for c in it['evidence_polarity_changed']
                        ]
                        extras.append(f"polarity {changes}")
                    if extras:
                        line += f" ({'; '.join(extras)})"
                    parts.append(line)
        parts.append('')
    parts.append('## Broken references')
    parts.append('')
    refs = last_diff_dict.get('broken_references') or []
    if not refs:
        parts.append('None.')
    else:
        for r in refs:
            if isinstance(r, dict):
                parts.append(f"- {r.get('from_id', '')}: {r.get('missing_id', '')} ({r.get('field_name', '')})")
            else:
                parts.append(f'- {r}')
    parts.append('')
    return '\n'.join(parts) + '\n'


def _render_contradiction_line(record):
    '''Render one contradiction record as a single markdown bullet.'''
    rule = record.get('rule')
    if rule in ('evidence_conflict', 'eroded_confidence'):
        return f"- {record['reason']} (evidence: {', '.join(record.get('evidence_ids') or [])})"
    if rule == 'orphaned_assumption':
        return f"- {record['reason']}"
    if rule == 'decision_basis_eroded':
        return (f"- decision {record['decision_id']}: basis eroded on "
                f"{record.get('depended_on_claim_id', '')} ({record.get('mode', '')}) -- {record['reason']}")
    if rule == 'claim_unchanged':
        ev = ', '.join(record.get('newer_evidence_ids') or [])
        return f"- claim {record['claim_id']}: unchanged despite newer linked evidence ({ev})"
    return f"- {record.get('reason', '')}"


def _render_computed_contradiction_body(contradictions):
    '''Grouped-by-rule contradiction body lines, shared by contradictions.md and
    current_state.md section 6. Each rule renders under its _CONTRADICTION_SECTIONS
    label; an all-empty set collapses to a single "No contradictions detected." line.'''
    lines = []
    if sum(len(v) for v in contradictions.values()) == 0:
        return ['No contradictions detected.', '']
    for key, label in _CONTRADICTION_SECTIONS:
        lines.append(f'### {label}')
        lines.append('')
        records = contradictions[key]
        if not records:
            lines.append('None.')
        else:
            for rec in records:
                lines.append(_render_contradiction_line(rec))
        lines.append('')
    return lines


def _render_falsification_block(rec):
    lines = [f"### {rec['claim_id']}", '']
    if rec.get('claim_title'):
        lines.append(f"- title: {rec['claim_title']}")
        lines.append('')
    lines.append('What would change my mind:')
    lines.append('')
    lines.append(rec.get('what_would_change_my_mind', ''))
    lines.append('')
    lines.append('Linked evidence (the agent judges whether any meets the condition; cofr issues no verdict):')
    for ev in rec.get('evidence', []):
        lines.append(f"- {ev['id']} [{ev.get('polarity', '')}, strength {ev.get('strength', '')}]: {ev.get('summary', '')}")
    return '\n'.join(lines)


def generate_contradictions(state, contradictions=None, falsification_review=None, computed_risks=None):
    '''Render artifacts/contradictions.md: computed contradictions, the
    agent-judged falsification review, computed risks, and user-authored risks.

    Computed and user-authored risks render in separate sections, labeled by
    source, matching the normalized records `cofr show risks --json` exposes.
    Precomputed contradictions / falsification_review / computed_risks are
    reused when supplied, so a caller that already has them avoids recomputing.'''
    from cofr.domain import is_live

    if contradictions is None:
        contradictions, _ = compute_contradictions(state)
    review = falsification_review if falsification_review is not None else compute_falsification_review(state)
    if computed_risks is None:
        computed_risks, _ = compute_computed_risks(state, contradictions=contradictions)
    authored_risks = sorted(
        (r for r in state.get('risks', [])
         if r.get('source', 'authored') == 'authored' and is_live(r, type_str='risk')),
        key=lambda x: x.get('id', ''),
    )

    parts = [HEADER, '', '# Contradictions', '']
    parts.append('## Computed contradictions')
    parts.append('')
    parts.extend(_render_computed_contradiction_body(contradictions))

    parts.append('## Falsification review')
    parts.append('')
    if not review:
        parts.append('None.')
        parts.append('')
    else:
        for rec in review:
            parts.append(_render_falsification_block(rec))
            parts.append('')

    parts.append('## Computed risks')
    parts.append('')
    if not computed_risks:
        parts.append('No computed risks.')
        parts.append('')
    else:
        for r in computed_risks:
            parts.append(_render_risk_block(r))
            parts.append('')

    parts.append('## User-identified risks')
    parts.append('')
    if not authored_risks:
        parts.append('No user-authored risks.')
        parts.append('')
    else:
        for r in authored_risks:
            parts.append(_render_risk_block(r))
            parts.append('')

    return '\n'.join(parts) + '\n'


def _render_next_decision_candidate(entry, abbreviated=False):
    rec = entry['record']
    lines = [f"### {entry['id']}", '']
    lines.append(f"- kind: {entry['kind']}")
    lines.append(f"- score: {entry['score']}")
    if entry['related_claims']:
        rc = ', '.join(f"{c['id']} ({c['status']})" for c in entry['related_claims'])
        lines.append(f"- related claims: {rc}")
    if entry['kind'] == 'question':
        if rec.get('question'):
            lines.extend(['', 'Question:', '', rec['question']])
        if not abbreviated and rec.get('blocking_impact'):
            lines.extend(['', 'Blocking impact:', '', rec['blocking_impact']])
        if not abbreviated and rec.get('proposed_resolution'):
            lines.extend(['', 'Proposed resolution:', '', rec['proposed_resolution']])
        if not abbreviated and rec.get('minimum_test'):
            lines.extend(['', 'Minimum test:', '', rec['minimum_test']])
    else:
        if rec.get('title'):
            lines.append(f"- title: {rec['title']}")
        for e in entry.get('eroded_basis') or []:
            lines.append(f"- stale basis: claim {e.get('depended_on_claim_id', '')} ({e.get('mode', '')}) -- {e.get('reason', '')}")
        if rec.get('decision_statement'):
            lines.extend(['', 'Decision:', '', rec['decision_statement']])
        if not abbreviated and rec.get('reopen_conditions'):
            lines.extend(['', 'Reopen conditions:', '', rec['reopen_conditions']])
    return '\n'.join(lines)


def generate_next_decision(state, contradictions=None):
    '''Render artifacts/next_decision.md: the ranked next-decision scaffold.'''
    ranked, rationale_lines, _ = rank_next_decisions(state, contradictions=contradictions)

    parts = [HEADER, '', '# Recommended next decision', '']
    parts.append('## Top decision')
    parts.append('')
    if not ranked:
        parts.append('No decision to recommend -- no open questions and no decisions with eroded basis.')
        parts.append('')
    else:
        parts.append(_render_next_decision_candidate(ranked[0]))
        parts.append('')

    parts.append('## Runner-up decisions')
    parts.append('')
    runner_ups = ranked[1:4]
    if not runner_ups:
        parts.append('None.')
        parts.append('')
    else:
        for entry in runner_ups:
            parts.append(_render_next_decision_candidate(entry, abbreviated=True))
            parts.append('')

    parts.append('## Ranking rationale')
    parts.append('')
    for line in rationale_lines:
        parts.append(line)
    parts.append('')

    return '\n'.join(parts) + '\n'
